### ISSUE TITLE
Missing license.

### ISSUE THREAD

**Issue by ljmc-github** [mircare/Brewery#1]
Hi, I would really like to use Brewery for a project I will be starting soon, I noticed it does not have a license and that would be crucial for my project. Could you please add one ?
I know it is not always in simple to license in academia, but I can only recommend FSF licenses (https://www.gnu.org/licenses/licenses.html) to keep your code open.
Thanks in advance ! 
Regards, Louis

**Comment by mircare** [comment]
Hi,
Thank you for your interest! I am not very familiar with GitHub but you can find the license here https://github.com/mircare/Brewery#license
Best,
Mirko

**Comment by ljmc-github** [comment]
My bad. I hadn’t realised it was there. Normally a copy should be added as a LICENSE file in the root of the repo. I can PR it if you want, or you can add it.

**Comment by mircare** [comment]
Added (https://github.com/mircare/Brewery/commit/a073439e8a132a4d1ce8b3aafb1e5dfdbfb0a177). Thank you!
