### ISSUE TITLE
Brewery to evaluate conservation of secondary structure

### ISSUE THREAD

**Issue by gnmcsbnfrmtcsclb** [mircare/Brewery#2]
I wonder if Brewery tools would help me solve my problem, described in brief below:

I have predicted ~ 20K protein domain sequences by using a HMM query from Pfam, and proteomes as queried databases.

Amongst the putative matches reported:

- most are shorter in length (peak at ~37aa, as short as 17aa), 
- a small fraction are much longer (up to 87aa), and 
- rarely they match canonical length of the HMM query (48aa).

I want to check how many of these predicted domain sequences have conserved protein secondary structure, so one idea was to use hhblits to generate a HHM-HMM pairwise alignment and parse it.

But that idea also comes with more questions that I am looking to answer. (`https://www.biostars.org/p/387607/#387854`)

While looking for those answers, I came across your GitHub account, and wonder if you have any advice about using any of your tools (Brewery) or other tools to help me "**evaluate degree of conservation of predicted SS for my input sequences**"?

Thank you, in advance!

**Comment by mircare** [comment]
The first thing that comes to my mind is to take into consideration the "confidence" of the predicted SS - something like what HHblits gives you in output, thanks to PSIPRED. However, we have not analyzed this particular aspect and cannot say how much strong, if any, the link between the confidence of the predicted SS and the degree of conservation is.

I did run Brewery on the human proteome so I can send you those predictions if you like.

**Comment by gnmcsbnfrmtcsclb** [comment]
Yes, please. I'd appreciate if you can also share the **steps** and **syntax** used to generate Brewery results for the human proteome, apart from the human proteome Brewery SS data itself. Thank you!

**Comment by mircare** [comment]
You can download it from http://distilldeep.ucd.ie/brewery/HumanProteome.tgz (933MB).

If you want to reproduce these results, you first need to setup Brewery as explained here: https://github.com/mircare/Brewery#setup. You can then run Brewery sequentially on each FASTA file as follow:
`$ for f in Fasta/*; do python3 Brewery/Brewery.py -i $f --cpu 8; done`
